### ISSUE TITLE
Generate attestation bundle at verification time (Verification Attestations)

### ISSUE THREAD

**Issue by mikhailswift** [in-toto/witness#14]
Migrated from gitlab -- original author @mikhailswift 

During witness verify we could bundle attestations that were used to satisfy a policy.  This bundle could then be signed with an expiration to be used as proof that it satisfies the policy.  

Signed or unsigned the bundle could be used to re-evaluate the policy and ensure everything passes.

SLSA has a concept of a bundle that may fit this use case: https://github.com/slsa-framework/slsa/blob/main/controls/attestations.md#compound-statement

**Comment by colek42** [comment]
@sudobmitch has a great talk on how we can attach artifacts to OCI images.  https://www.youtube.com/watch?v=_c1OdmP9Ssg
