### ISSUE TITLE
SLSA Provenance Attestation

### ISSUE THREAD

**Issue by colek42** [in-toto/witness#217]
Proposal:

Witness should use information in the attestation context to create an SLSA Provenance document.

https://slsa.dev/provenance/v0.1

**Comment by colek42** [comment]
This will be completed as a optional output attestor that scrapes data from the other attestors

**Comment by garethahealy** [comment]
whats the status of this?

**Comment by rrey** [comment]
👋 Also interesting in getting Provenance with witness.

**Comment by jkjell** [comment]
Closed by https://github.com/in-toto/witness/pull/381 and include in Witness `v0.4.0` and later.
