### ISSUE TITLE
install-witness shell script fails to curl checksums file

### ISSUE THREAD

**Issue by jonathan-dorsey** [in-toto/witness#263]
The install script has an invalid path for the checksums files (- vs _) which causes the script to fail.

**Comment by jonathan-dorsey** [comment]
Started to resolve this with #264, but realized that the checksums file actually contains checksums for a rc1 file which doesn't match the checksum of the released binaries.

**Comment by colek42** [comment]
Thank you.  We are in the process of updating our release process, we will add this to the next release.

**Comment by jkjell** [comment]
Just ran into this for myself.  I'll start digging into the updated release process soon.

**Comment by matglas** [comment]
I just ran it and I think this can be closed. It works at least at this moment.

**Comment by matglas** [comment]
Verify interestingly I just had the same problem. I found one issue indeed. The first curl could use a `-L` to make sure it redirects correctly.
