### ISSUE TITLE
[Feat]: enhanced debug log level output

### ISSUE THREAD

**Issue by Strakeln** [in-toto/witness#375]
**Describe the solution you'd like:**

When using `debug` log level for `witness verify`, output each step in the verification process for better debugging. 

The verification process is described [here](https://github.com/in-toto/witness/blob/main/docs/concepts/policy.md#verification-process). If there was debug output for each of the five steps, it might help users debug the failures they are experiencing.

**User value:**

Currently, with debug log level enabled, we only learn that there was a failure, but do not know where in the process the failure occurred. If there were step-specific output, the user might be able to more quickly hone in on where the problem lies.

**Expected behavior:**

Specifying `-l debug` to `witness verify` results in per-step outputs and success/failure indications. The primary desire here is outputs for each of the verification steps, but outputs for steps-within-the-steps might also be helpful.

**Proposed solution:**

Add at least one debug output for each verification step.

**Testing changes required:**

Verify that specifying `-l debug` to `witness verify` results in outputs from each of the verification steps (currently 5 steps)

**Documentation changes required:**

None

**Comment by matglas** [comment]
@Strakeln if you are able to build yourself a new version you can test the new functionality that has been added. Please give it a try. I was very happy with the results from the work @ChaosInTheCRD did.

**Comment by Strakeln** [comment]
@matglas @ChaosInTheCRD - Sorry for the delayed response, I have been out of office for a few weeks to move to a new house. I tested out witness 0.4.0 and I have to say, I LOVE the improvements to the debug logs. It is a substantial and meaningful improvement. Thank you, and well done!
