### ISSUE TITLE
User should be able to set what algos to use for digest calculation in config file

### ISSUE THREAD

**Issue by colek42** [in-toto/witness#73]

**Comment by DataDavD** [comment]
Is anyone working on this? I can take a look sometime next couple weeks, if no one else is

**Comment by jkjell** [comment]
Appreciate the help @DataDavD. Let us know if you have any questions or need any help along the way.

**Comment by DataDavD** [comment]
Just realized this probably needs to be in the `go-witness` repo based on me looking around the two repos. I'm guessing the pkg code was split into go-witness? (side question: any history about why that was done and not just kept with the `witness` repo)

**Comment by mikhailswift** [comment]
Hi @DataDavD! Thanks for taking a look into this.

You should be able to use the `[RunWithAttestationOptions](https://github.com/testifysec/go-witness/blob/03cf3f0235b0a59d873aa6b91a56ffe08c7e7f6d/run.go#L46)` function when calling `go-witness.Run`. In that function, you can supply the `[attestation.WithHashes](https://github.com/testifysec/go-witness/blob/03cf3f0235b0a59d873aa6b91a56ffe08c7e7f6d/attestation/context.go#L59)` with a slice of the hash functions. This will pass through the hashes to the `AttestationContext` that `Run` creates for you.

As for why Witness and go-witness got split: We wanted to use go-witness in other applications, but some of Witness's go-modules were causing issues. Along that same thread, we tried to keep the go-witness dependencies lighter than what Witness as a whole would use -- for instance, we didn't want the library to be opinionated about what logging library was used.

Hopefully, this answers your question, and again thanks so much for looking into this.

**Comment by DataDavD** [comment]
Hey, just a small update. Starting digging in. Should have something more concrete, or more concrete questions later this weekend. Thanks again!

**Comment by DataDavD** [comment]
Hey @mikhailswift. Maybe I'm confused, but is the expectation to have the availability of adding algos cobra.Command run parts like here: https://github.com/testifysec/witness/blob/4a41144b6402e7d175a657a359a66b41022dccd4/cmd/run.go#L111

Thanks,
dd

**Comment by mikhailswift** [comment]
Sorry, I did miss that. I think you're on the right path. My only suggestion would be to have `[]string{"sha256"}` be the default of the cobra variable. This should allow for it to be defined through either the CLI or a config file and not change our default behavior of using sha256 out of the box.

**Comment by DataDavD** [comment]
Oh no problem at all. 

Got it, makes more sense. I'll make those changes. 

Thank you

**Comment by jkjell** [comment]
Closed by https://github.com/in-toto/witness/pull/292
